/*
 File:          recursion.h
 Purpose:       Prototypes for lab 4 exercises
 Author:	Idil Bil and Fatima Mustaq
 Date:		November 16, 2021
 */

#pragma once

/******************************************************************
 PLEASE DO NOT EDIT THIS FILE
 ******************************************************************/

int calculate_power(int base, int power);
int count_digits(int number);
int string_length( char* string );
int is_palindrome(char* string, int string_length);
int draw_ramp( int number, char* buffer );
int draw_row( int size, char* buffer );
